const mongoose = require('mongoose');

const orderSchema = new mongoose.Schema({
  productName: { type: String, required: true },
  supplier: { type: String, required: true },
  quantity: { type: Number, required: true },
  unitPrice: { type: Number, required: true },
  totalAmount: { type: Number, required: true },
  status: { type: String, enum: ['pending', 'approved', 'placed', 'delivered', 'rejected'], default: 'pending' },
  orderDate: { type: Date, required: true },
  expectedDelivery: { type: Date, required: true },
  priority: { type: String, enum: ['high', 'medium', 'low'], default: 'medium' },
  autoGenerated: { type: Boolean, default: false },
  approvedBy: { type: String, default: null },
  notes: { type: String, default: '' }
}, { timestamps: true });

module.exports = mongoose.model('Order', orderSchema); 