import React, { useState, useEffect } from 'react';
import { 
  CheckCircle, 
  Clock, 
  AlertTriangle, 
  X, 
  Eye,
  Download,
  Search,
  Package,
  Calendar,
  Truck,
  User
} from 'lucide-react';
import toast from 'react-hot-toast';
import { orderAPI } from '../services/api';
import Modal from '../components/Modal'; // If you don't have a Modal component, use a simple div for the modal

const OrderManagement = () => {
  const [orders, setOrders] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedStatus, setSelectedStatus] = useState('all');
  const [selectedSupplier, setSelectedSupplier] = useState('all');
  const [loading, setLoading] = useState(false);
  const [addModalOpen, setAddModalOpen] = useState(false);
  const [newOrder, setNewOrder] = useState({
    productName: '',
    supplier: '',
    quantity: '',
    unitPrice: '',
    totalAmount: '',
    status: 'pending',
    orderDate: '',
    expectedDelivery: '',
    priority: 'medium',
    autoGenerated: false,
    approvedBy: null,
    notes: ''
  });

  useEffect(() => {
    fetchOrders();
  }, []);

  const fetchOrders = async () => {
    setLoading(true);
    try {
      const res = await orderAPI.getOrders();
      setOrders(res.orders || []);
    } catch (e) {
      toast.error('Failed to load orders');
    } finally {
      setLoading(false);
    }
  };

  const statuses = ['all', 'pending', 'approved', 'placed', 'delivered', 'rejected'];
  const suppliers = ['all', ...Array.from(new Set(orders.map(o => o.supplier)))];

  const filteredOrders = orders.filter(order => {
    const matchesSearch = order.productName.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         order._id.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = selectedStatus === 'all' || order.status === selectedStatus;
    const matchesSupplier = selectedSupplier === 'all' || order.supplier === selectedSupplier;
    return matchesSearch && matchesStatus && matchesSupplier;
  });

  const getStatusColor = (status) => {
    switch (status) {
      case 'pending': return 'text-warning-600 bg-warning-50';
      case 'approved': return 'text-primary-600 bg-primary-50';
      case 'placed': return 'text-success-600 bg-success-50';
      case 'delivered': return 'text-success-600 bg-success-50';
      case 'rejected': return 'text-danger-600 bg-danger-50';
      default: return 'text-gray-600 bg-gray-50';
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'pending': return Clock;
      case 'approved': return CheckCircle;
      case 'placed': return Truck;
      case 'delivered': return CheckCircle;
      case 'rejected': return X;
      default: return Clock;
    }
  };

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'high': return 'text-danger-600 bg-danger-50';
      case 'medium': return 'text-warning-600 bg-warning-50';
      case 'low': return 'text-success-600 bg-success-50';
      default: return 'text-gray-600 bg-gray-50';
    }
  };

  const handleApprove = async (id) => {
    try {
      await orderAPI.approveOrder(id);
      toast.success(`Order approved successfully!`);
      fetchOrders();
    } catch (e) {
      toast.error('Failed to approve order');
    }
  };

  const handleReject = async (id) => {
    try {
      await orderAPI.rejectOrder(id);
      toast.error(`Order rejected!`);
      fetchOrders();
    } catch (e) {
      toast.error('Failed to reject order');
    }
  };

  const handleViewDetails = (id) => {
    toast.info(`Viewing details for order ${id}`);
  };

  const handleDownload = (id) => {
    toast.success(`Downloading order ${id} as PDF`);
  };

  const handleDeleteOrder = async (id) => {
    if (!window.confirm('Delete this order?')) return;
    try {
      await orderAPI.deleteOrder(id);
      toast.success('Order deleted');
      fetchOrders();
    } catch (e) {
      toast.error('Failed to delete order');
    }
  };

  const handleAddOrderChange = (e) => {
    const { name, value, type, checked } = e.target;
    setNewOrder((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
    if (name === 'quantity' || name === 'unitPrice') {
      const quantity = name === 'quantity' ? value : newOrder.quantity;
      const unitPrice = name === 'unitPrice' ? value : newOrder.unitPrice;
      setNewOrder((prev) => ({
        ...prev,
        totalAmount: quantity && unitPrice ? (parseFloat(quantity) * parseFloat(unitPrice)).toFixed(2) : ''
      }));
    }
  };
  const handleAddOrder = async (e) => {
    e.preventDefault();
    try {
      const orderData = {
        ...newOrder,
        quantity: parseInt(newOrder.quantity, 10),
        unitPrice: parseFloat(newOrder.unitPrice),
        totalAmount: parseFloat(newOrder.totalAmount),
        orderDate: newOrder.orderDate ? new Date(newOrder.orderDate) : new Date(),
        expectedDelivery: newOrder.expectedDelivery ? new Date(newOrder.expectedDelivery) : new Date(),
      };
      await orderAPI.createOrder(orderData);
      toast.success('Order created');
      setAddModalOpen(false);
      setNewOrder({
        productName: '',
        supplier: '',
        quantity: '',
        unitPrice: '',
        totalAmount: '',
        status: 'pending',
        orderDate: '',
        expectedDelivery: '',
        priority: 'medium',
        autoGenerated: false,
        approvedBy: null,
        notes: ''
      });
      fetchOrders();
    } catch (e) {
      toast.error('Failed to create order');
    }
  };

  const getTotalOrders = () => filteredOrders.length;
  const getTotalValue = () => filteredOrders.reduce((sum, order) => sum + order.totalAmount, 0);
  const getPendingOrders = () => filteredOrders.filter(order => order.status === 'pending').length;
  const getDeliveredOrders = () => filteredOrders.filter(order => order.status === 'delivered').length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Order Management</h1>
          <p className="text-gray-600">Manage auto-generated and manual purchase orders</p>
        </div>
        <button className="btn-primary" onClick={() => setAddModalOpen(true)}>+ Add Order</button>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="card text-center">
          <div className="text-2xl font-bold text-primary-600">{getTotalOrders()}</div>
          <div className="text-sm text-gray-600">Total Orders</div>
        </div>
        <div className="card text-center">
          <div className="text-2xl font-bold text-success-600">${getTotalValue().toLocaleString()}</div>
          <div className="text-sm text-gray-600">Total Value</div>
        </div>
        <div className="card text-center">
          <div className="text-2xl font-bold text-warning-600">{getPendingOrders()}</div>
          <div className="text-sm text-gray-600">Pending Approval</div>
        </div>
        <div className="card text-center">
          <div className="text-2xl font-bold text-success-600">{getDeliveredOrders()}</div>
          <div className="text-sm text-gray-600">Delivered</div>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="flex flex-wrap gap-4 items-center">
        <div className="flex items-center gap-2">
          <Search className="h-4 w-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search orders..."
            value={searchTerm}
            onChange={e => setSearchTerm(e.target.value)}
            className="input-field"
          />
        </div>
        <select value={selectedStatus} onChange={e => setSelectedStatus(e.target.value)} className="input-field">
          {statuses.map(status => (
            <option key={status} value={status}>{status.charAt(0).toUpperCase() + status.slice(1)}</option>
          ))}
        </select>
        <select value={selectedSupplier} onChange={e => setSelectedSupplier(e.target.value)} className="input-field">
          {suppliers.map(supplier => (
            <option key={supplier} value={supplier}>{supplier}</option>
          ))}
        </select>
      </div>

      {/* Orders Table */}
      <div className="card overflow-x-auto">
        {loading ? (
          <div>Loading orders...</div>
        ) : (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="table-header">Order</th>
                <th className="table-header">Supplier</th>
                <th className="table-header">Quantity</th>
                <th className="table-header">Status</th>
                <th className="table-header">Priority</th>
                <th className="table-header">Order Date</th>
                <th className="table-header">Expected Delivery</th>
                <th className="table-header">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredOrders.map(order => {
                const StatusIcon = getStatusIcon(order.status);
                return (
                  <tr key={order._id} className="hover:bg-gray-50">
                    <td className="table-cell">
                      <div>
                        <div className="font-medium text-gray-900">{order.productName}</div>
                        <div className="text-sm text-gray-500">ID: {order._id}</div>
                        <div className="flex items-center mt-1">
                          {order.autoGenerated ? (
                            <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-primary-100 text-primary-800">
                              <Package className="h-3 w-3 mr-1" />
                              Auto-Generated
                            </span>
                          ) : (
                            <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                              <User className="h-3 w-3 mr-1" />
                              Manual
                            </span>
                          )}
                        </div>
                      </div>
                    </td>
                    <td className="table-cell">
                      <div className="text-sm text-gray-900">{order.supplier}</div>
                    </td>
                    <td className="table-cell">
                      <div className="text-sm text-gray-900">{order.quantity} units</div>
                      <div className="text-sm text-gray-500">${order.unitPrice}/unit</div>
                      <div className="text-sm font-medium text-gray-900">${order.totalAmount}</div>
                    </td>
                    <td className="table-cell">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(order.status)}`}>
                        <StatusIcon className="h-3 w-3 mr-1" />
                        {order.status.charAt(0).toUpperCase() + order.status.slice(1)}
                      </span>
                    </td>
                    <td className="table-cell">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getPriorityColor(order.priority)}`}>
                        {order.priority.charAt(0).toUpperCase() + order.priority.slice(1)}
                      </span>
                    </td>
                    <td className="table-cell">
                      <div className="text-sm text-gray-900">{new Date(order.orderDate).toLocaleDateString()}</div>
                    </td>
                    <td className="table-cell">
                      <div className="text-sm text-gray-900">{new Date(order.expectedDelivery).toLocaleDateString()}</div>
                    </td>
                    <td className="table-cell">
                      <div className="flex space-x-2">
                        {order.status === 'pending' && (
                          <button className="btn-primary btn-xs" onClick={() => handleApprove(order._id)}>Approve</button>
                        )}
                        {order.status === 'pending' && (
                          <button className="btn-danger btn-xs" onClick={() => handleReject(order._id)}>Reject</button>
                        )}
                        <button className="btn-secondary btn-xs" onClick={() => handleViewDetails(order._id)}><Eye className="h-4 w-4" /></button>
                        <button className="btn-secondary btn-xs" onClick={() => handleDownload(order._id)}><Download className="h-4 w-4" /></button>
                        <button className="btn-danger btn-xs" onClick={() => handleDeleteOrder(order._id)}><X className="h-4 w-4" /></button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </div>
      {addModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-30">
          <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-md relative">
            <button className="absolute top-2 right-2 text-gray-400 hover:text-gray-600" onClick={() => setAddModalOpen(false)}><X /></button>
            <h3 className="text-lg font-semibold mb-4">Add New Order</h3>
            <form onSubmit={handleAddOrder} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Product Name</label>
                <input name="productName" value={newOrder.productName} onChange={handleAddOrderChange} className="input-field w-full" required />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Supplier</label>
                <input name="supplier" value={newOrder.supplier} onChange={handleAddOrderChange} className="input-field w-full" required />
              </div>
              <div className="flex gap-2">
                <div className="flex-1">
                  <label className="block text-sm font-medium text-gray-700 mb-1">Quantity</label>
                  <input name="quantity" type="number" min="1" value={newOrder.quantity} onChange={handleAddOrderChange} className="input-field w-full" required />
                </div>
                <div className="flex-1">
                  <label className="block text-sm font-medium text-gray-700 mb-1">Unit Price</label>
                  <input name="unitPrice" type="number" min="0" step="0.01" value={newOrder.unitPrice} onChange={handleAddOrderChange} className="input-field w-full" required />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Total Amount</label>
                <input name="totalAmount" type="number" min="0" step="0.01" value={newOrder.totalAmount} className="input-field w-full" readOnly />
              </div>
              <div className="flex gap-2">
                <div className="flex-1">
                  <label className="block text-sm font-medium text-gray-700 mb-1">Order Date</label>
                  <input name="orderDate" type="date" value={newOrder.orderDate} onChange={handleAddOrderChange} className="input-field w-full" required />
                </div>
                <div className="flex-1">
                  <label className="block text-sm font-medium text-gray-700 mb-1">Expected Delivery</label>
                  <input name="expectedDelivery" type="date" value={newOrder.expectedDelivery} onChange={handleAddOrderChange} className="input-field w-full" required />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Priority</label>
                <select name="priority" value={newOrder.priority} onChange={handleAddOrderChange} className="input-field w-full">
                  <option value="high">High</option>
                  <option value="medium">Medium</option>
                  <option value="low">Low</option>
                </select>
              </div>
              <div className="flex items-center gap-2">
                <input name="autoGenerated" type="checkbox" checked={newOrder.autoGenerated} onChange={handleAddOrderChange} />
                <label className="text-sm">Auto-Generated</label>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                <textarea name="notes" value={newOrder.notes} onChange={handleAddOrderChange} className="input-field w-full" rows={2} />
              </div>
              <div className="flex justify-end">
                <button type="submit" className="btn-primary px-4 py-2">Create Order</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default OrderManagement; 